### ISSUE TITLE
运行后提示OS Error occurred!

### ISSUE THREAD

**Issue by zzc-river** [coffeeandsecurity/DakshSCRA#1]
运行后如下图所示：
![image](https://github.com/coffeeandsecurity/DakshSCRA/assets/34366651/6b4fb1b3-e4df-4358-9ec2-d67ede23224d)

**Comment by coffeeandsecurity** [comment]
Thanks for submitting this issue. 

Looks like a parsing error caused due to unsupported encoding type. I have pushed v0.15 with some code changes to display a bit more specific error. Do download the latest version and run the tool. If you see any error, do share the details. 

Also, to further investigate and recreate the problem, Can you please email the source code to d3basis.m0hanty@gmail.com? If you prefer not to share the entire code base, it would suffice to provide 5-10 code files where you have encountered the error. If you are unable to send the source, provide details such as the OS you are using, the platform (PHP/.NET), total number of files, and any log files generated within the '/runtime' directory. Additionally, share the text report generated under '/DakshSCRA/reports/text'.

**Comment by coffeeandsecurity** [comment]
Closing the issue as I haven't heard back yet.
