### ISSUE TITLE
Environment error

### ISSUE THREAD

**Issue by KAYY123** [coffeeandsecurity/DakshSCRA#2]
Hello, I would like to ask if an error occurred while running the code. I executed sudo apt install libglib2.0-0, but the same error still occurred. What should I do？
![图片](https://github.com/coffeeandsecurity/DakshSCRA/assets/59907326/844082fc-185d-4b68-bea5-cf22685f2527)

**Comment by coffeeandsecurity** [comment]
Hi,

It seems like you’re installing dependencies outside the virtual environment but attempting to run the tool from within it.

I recommend installing the dependencies using `pip install` within the virtual environment. You can uninstall the library and then use `pip install -r requirements.txt` while you’re within the virtual environment to automatically install all dependencies.

Let me know if this resolves the issue.

**Comment by KAYY123** [comment]
Thank you, I have resolved this issue. However, I tried a lot of code but couldn't find any vulnerabilities. Can you provide some examples of code that detected vulnerabilities？

**Comment by KAYY123** [comment]
For example, can the online book store/secure/project code in the report be provided?

**Comment by KAYY123** [comment]
Hello, I have read the code and would like to ask if this is purely a rule matching? For example, any PHP code containing $_GET is considered to have a vulnerability

**Comment by coffeeandsecurity** [comment]
> Thank you, I have resolved this issue. However, I tried a lot of code but couldn't find any vulnerabilities. Can you provide some examples of code that detected vulnerabilities？

I recommend downloading some sample codes from GitHub itself. For instance, you can explore PHP applications available at https://github.com/search?q=online-book-store+language%3APHP&type=repositories&l=PHP

You can find the specific sample used in the report here: https://github.com/projectworlds32/online-book-store-project-in-php/archive/master.zip

**Comment by coffeeandsecurity** [comment]
> Hello, I have read the code and would like to ask if this is purely a rule matching? For example, any PHP code containing $_GET is considered to have a vulnerability

Sorry for the late response. 

Daksh SCRA distinguishes itself from traditional code review tools through its nuanced approach to identifying potential bugs. Rather than flagging everything that matches a specific rule pattern as a bug, it highlights points of interest that warrant closer examination. While there are rules files for each supported platform, they are utilized by the tool to pinpoint areas requiring manual inspection.

The generated report includes guidance notes for both developers and security reviewers, directing their attention to specific areas for potential bugs related to identified points of interest. For example, if the tool detects $_GET in PHP code, it flags it as a point of interest for manual inspection to confirm the presence of any bugs.

This approach empowers code reviewers with greater control over accurate findings. By examining the code from the perspective of identified points of interest, reviewers can reduce false positives, particularly as they become more familiar with the codebase.

**Comment by coffeeandsecurity** [comment]
> Hello, I have read the code and would like to ask if this is purely a rule matching? For example, any PHP code containing $_GET is considered to have a vulnerability

I realise, I missed responding to this query. 

Daksh SCRA stands apart from traditional code review tools by adopting a nuanced approach to identifying potential bugs. Instead of flagging everything that matches a particular pattern as a bug, it highlights points of interest that merit closer inspection. The generated report includes guidance notes for both developers and security reviewers, outlining specific areas to scrutinize for potential bugs related to the identified points of interest.

For instance, if the tool detects something like a $_GET in PHP, it flags it as a point of interest for manual inspection to confirm the presence of any bugs.

This approach offers code reviewers greater control over accurate findings. By examining the code from the perspective of identified points of interest, reviewers can minimize false positives, especially as they become more familiar with the codebase.
