### ISSUE TITLE
Does the tool support C or C++ detection?

### ISSUE THREAD

**Issue by JIE-sakura** [coffeeandsecurity/DakshSCRA#6]
Does the tool support C or C++ detection?

**Comment by coffeeandsecurity** [comment]
The support for C and C++ scanning was initially planned for a much later stage. However, since you expressed interest, I took some time to upload a few C and C++ rules and added preliminary scanning support.

Please note that the current set of rules is not extensive. I have only included a few rules to get you started, but I will add more as time permits.

The C rules are well-tested, so feel free to scan C sources. For C++ rules, I recommend downloading a fresh copy in a few days, as I still need to conduct proper testing on them.

To scan C sources, use the following command:
`python3 dakshscra.py -r c -t <path to source directory>`

Let me know if you encounter any issues or need further assistance.

**Note:** Currently, there is no support for scanning C and C++ together by merging their rules. Some rules may apply to both languages, but this feature will be introduced in the future. Once available, you will be able to specify 'c-cpp' as the rule type, and the tool will merge both rule sets before scanning. Architecture changes to support this feature are already underway.

**Comment by coffeeandsecurity** [comment]
**Update:**
The C++ rules have been tested, and scanning now works without errors. As mentioned earlier, only a few rules have been included for both C and C++ as part of this preliminary release. I’ll continue to expand these rule sets over time.

The process for adding new rules ensures that each rule translates into a meaningful check to identify potential or confirmed security hotspots that require inspection for weaknesses or bugs.
